CREATE TABLE IF NOT EXISTS book (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    price REAL NOT NULL,
    items_number INTEGER NOT NULL DEFAULT 1,
    total_price REAL NOT NULL,
    buyedat TIMESTAMP NOT NULL DEFAULT CURRENT_DATE
);
